name: Сборка и релиз

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Настройка JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Изменение прав доступа на gradlew
        run: chmod +x gradlew

      - name: Сборка с Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Проверка наличия JAR файла
        run: ls -la build/libs

      - name: Извлечение названия проекта и версии
        id: get_project_info
        run: |
          PROJECT_NAME=$(grep "^rootProject.name" settings.gradle | cut -d"'" -f2)
          VERSION=$(grep "^version" build.gradle | cut -d"'" -f2)
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Создание релиза на GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.VERSION }}
          body: |
            Релиз версии ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Загрузка JAR файла в релиз
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/*-${{ env.VERSION }}.jar
          asset_name: ${{ env.PROJECT_NAME }}-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
